language: php
php:
  - 7.1
before_install:
    - 'echo "$PREFIX Before intall"'
install:
    - 'echo "$PREFIX At Install"'
before_script:
    - 'echo "$PREFIX Before script"'
script:
    - 'echo "$PREFIX At script"'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "$PREFIX This is a PR, it is: $TRAVIS_PULL_REQUEST"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$PREFIX This is not a PR"; fi'
    - 'if [ "$TRAVIS_TAG" != "" ]; then echo "$PREFIX This is a tag and its name is: >> $TRAVIS_TAG << "; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then echo "$PREFIX Build is Merged into master"; fi'
after_script:
    - 'echo "$PREFIX After script"'
after_success:
    - 'echo "$PREFIX After success"'
after_failure:
    - 'echo "$PREFIX After failure"'
before_deploy:
    - 'echo "$PREFIX After deploy"'
#deploy:
#    provider: ....
#after_deploy:
#    - echo "After deploy"
before_cache:
    - 'echo "$PREFIX Before cache is triggered"'
env:
  - PREFIX=" >---Output---> "
